dist: xenial
language: ruby
sudo: false

cache: bundler

bundler_args: --jobs 3 --retry 3

before_install:
  - 'travis_retry gem update --system'
  - 'travis_retry gem install bundler'

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  fast_finish: true
