language: ruby

sudo: false

cache: bundler

script: 'bundle exec rake'

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  fast_finish: true
